#!/usr/bin/env node
/**
 * Turns the site password into something the browser can check, without the
 * password itself ever reaching the repository or the bundle.
 *
 * The password lives in `.env` locally and in the `SITE_PASSWORD` repository
 * secret in CI. This script derives a PBKDF2 key from it and writes that key
 * into `src/app/core/gate-key.ts`, which is generated and git-ignored. The
 * shipped JavaScript therefore contains a derived key and nothing else.
 *
 * Be clear about what this is: a lock on the front door of a static site. The
 * check runs in the visitor's browser, so anyone willing to open the developer
 * tools can step around it. It keeps the site away from people who wandered in
 * and away from search engines. It is not a way to publish secrets.
 */
import { pbkdf2Sync } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Used when nothing supplies one, so a fresh clone still builds and runs. */
const FALLBACK = 'asd987';

/**
 * Public by design: a salt only has to be unique to this site, so that a
 * ready-made table of common passwords does not match the key we ship.
 */
const SALT = 'apex-developments/gate/v1';

/** Enough work that guessing at the key is slow, little enough that a real
 *  visitor does not notice the wait. */
const ITERATIONS = 200_000;

function fromDotEnv() {
  const file = join(root, '.env');
  if (!existsSync(file)) return undefined;
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = /^\s*(?:export\s+)?SITE_PASSWORD\s*=\s*(.*)$/.exec(line);
    if (!m) continue;
    return m[1].trim().replace(/^(['"])(.*)\1$/, '$2');
  }
  return undefined;
}

const password = process.env.SITE_PASSWORD?.trim() || fromDotEnv() || FALLBACK;
const key = pbkdf2Sync(password, SALT, ITERATIONS, 32, 'sha256').toString('hex');

writeFileSync(
  join(root, 'src/app/core/gate-key.ts'),
  `// Generated by scripts/gate-key.mjs. Do not edit, and do not commit.
// The password itself is in .env locally, and in the SITE_PASSWORD secret in CI.
export const GATE_KEY = '${key}';
export const GATE_SALT = '${SALT}';
export const GATE_ITERATIONS = ${ITERATIONS};
`,
  'utf8',
);

const where = process.env.SITE_PASSWORD ? 'the environment' : fromDotEnv() ? '.env' : 'the built-in fallback';
console.log(`gate key written from ${where}`);
