import { Area, FaqItem, Pillar, ProcessStep, Project, Testimonial } from './models';
import { grossYieldPct, netYieldPct } from './yield-model';

const IMG = 'img';

export const AREAS: Area[] = [
  {
    id: 'canggu',
    name: 'area.canggu.name',
    subtitle: 'area.canggu.subtitle',
    image: `${IMG}/canggu.jpg`,
    tagline: 'area.canggu.tagline',
    description: 'area.canggu.description',
    landPriceArePerYearUsd: 1850,
    avgNightlyRateUsd: 285,
    occupancy: 0.82,
    driveToAirportMin: 45,
    bestFor: ['area.canggu.bestFor1', 'area.canggu.bestFor2', 'area.canggu.bestFor3'],
  },
  {
    id: 'pererenan',
    name: 'area.pererenan.name',
    subtitle: 'area.pererenan.subtitle',
    image: `${IMG}/canggu-2.jpg`,
    tagline: 'area.pererenan.tagline',
    description: 'area.pererenan.description',
    landPriceArePerYearUsd: 1400,
    avgNightlyRateUsd: 260,
    occupancy: 0.79,
    driveToAirportMin: 50,
    bestFor: ['area.pererenan.bestFor1', 'area.pererenan.bestFor2', 'area.pererenan.bestFor3'],
  },
  {
    id: 'seminyak',
    name: 'area.seminyak.name',
    subtitle: 'area.seminyak.subtitle',
    image: `${IMG}/seminyak.jpg`,
    tagline: 'area.seminyak.tagline',
    description: 'area.seminyak.description',
    landPriceArePerYearUsd: 2100,
    avgNightlyRateUsd: 310,
    occupancy: 0.77,
    driveToAirportMin: 30,
    bestFor: ['area.seminyak.bestFor1', 'area.seminyak.bestFor2', 'area.seminyak.bestFor3'],
  },
  {
    id: 'uluwatu',
    name: 'area.uluwatu.name',
    subtitle: 'area.uluwatu.subtitle',
    image: `${IMG}/uluwatu-cliffs.jpg`,
    tagline: 'area.uluwatu.tagline',
    description: 'area.uluwatu.description',
    landPriceArePerYearUsd: 1250,
    avgNightlyRateUsd: 395,
    occupancy: 0.74,
    driveToAirportMin: 40,
    bestFor: ['area.uluwatu.bestFor1', 'area.uluwatu.bestFor2', 'area.uluwatu.bestFor3'],
  },
  {
    id: 'ubud',
    name: 'area.ubud.name',
    subtitle: 'area.ubud.subtitle',
    image: `${IMG}/rice-tegalalang.jpg`,
    tagline: 'area.ubud.tagline',
    description: 'area.ubud.description',
    landPriceArePerYearUsd: 900,
    avgNightlyRateUsd: 240,
    occupancy: 0.8,
    driveToAirportMin: 75,
    bestFor: ['area.ubud.bestFor1', 'area.ubud.bestFor2', 'area.ubud.bestFor3'],
  },
  {
    id: 'sanur',
    name: 'area.sanur.name',
    subtitle: 'area.sanur.subtitle',
    image: `${IMG}/sanur.jpg`,
    tagline: 'area.sanur.tagline',
    description: 'area.sanur.description',
    landPriceArePerYearUsd: 1150,
    avgNightlyRateUsd: 215,
    occupancy: 0.81,
    driveToAirportMin: 35,
    bestFor: ['area.sanur.bestFor1', 'area.sanur.bestFor2', 'area.sanur.bestFor3'],
  },
  {
    id: 'nusa-dua',
    name: 'area.nusa-dua.name',
    subtitle: 'area.nusa-dua.subtitle',
    image: `${IMG}/nusa-dua.jpg`,
    tagline: 'area.nusa-dua.tagline',
    description: 'area.nusa-dua.description',
    landPriceArePerYearUsd: 1550,
    avgNightlyRateUsd: 330,
    occupancy: 0.76,
    driveToAirportMin: 20,
    bestFor: ['area.nusa-dua.bestFor1', 'area.nusa-dua.bestFor2', 'area.nusa-dua.bestFor3'],
  },
  {
    id: 'tabanan',
    name: 'area.tabanan.name',
    subtitle: 'area.tabanan.subtitle',
    image: `${IMG}/tanah-lot.jpg`,
    tagline: 'area.tabanan.tagline',
    description: 'area.tabanan.description',
    landPriceArePerYearUsd: 550,
    avgNightlyRateUsd: 195,
    occupancy: 0.68,
    driveToAirportMin: 70,
    bestFor: ['area.tabanan.bestFor1', 'area.tabanan.bestFor2', 'area.tabanan.bestFor3'],
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    slug: 'ombak-residences',
    pool: 'project.ombak-residences.pool',
    name: 'project.ombak-residences.name',
    area: 'pererenan',
    type: 'villa',
    status: 'construction',
    headline: 'project.ombak-residences.headline',
    summary: 'project.ombak-residences.summary',
    body: ['project.ombak-residences.body1', 'project.ombak-residences.body2', 'project.ombak-residences.body3'],
    hero: `${IMG}/villa-pool-deck.jpg`,
    gallery: [`${IMG}/villa-pool-deck.jpg`, `${IMG}/villa-living-pool.jpg`, `${IMG}/villa-master.jpg`, `${IMG}/villa-lawn.jpg`],
    priceFromUsd: 389000,
    landSqm: 350,
    builtSqm: 245,
    bedrooms: 3,
    bathrooms: 3,
    leaseYears: 25,
    leaseExtensionYears: 25,
    leaseStartYear: 2026,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.79,
    nightlyRateUsd: 295,
    handover: 'project.ombak-residences.handover',
    handoverOrder: 20271,
    progress: 35,
    unitsTotal: 4,
    unitsAvailable: 2,
    features: ['project.ombak-residences.feature1', 'project.ombak-residences.feature2', 'project.ombak-residences.feature3', 'project.ombak-residences.feature4', 'project.ombak-residences.feature5', 'project.ombak-residences.feature6'],
    timeline: [
      { date: 'project.ombak-residences.timeline1.date', title: 'project.ombak-residences.timeline1.title', note: 'project.ombak-residences.timeline1.note', progress: 8 },
      { date: 'project.ombak-residences.timeline2.date', title: 'project.ombak-residences.timeline2.title', note: 'project.ombak-residences.timeline2.note', progress: 18 },
      { date: 'project.ombak-residences.timeline3.date', title: 'project.ombak-residences.timeline3.title', note: 'project.ombak-residences.timeline3.note', progress: 35 },
      { date: 'project.ombak-residences.timeline4.date', title: 'project.ombak-residences.timeline4.title', note: 'project.ombak-residences.timeline4.note', progress: 60 },
    ],
  },
  {
    id: 'p2',
    slug: 'tebing-cliff-villas',
    pool: 'project.tebing-cliff-villas.pool',
    name: 'project.tebing-cliff-villas.name',
    area: 'uluwatu',
    type: 'villa',
    status: 'available',
    headline: 'project.tebing-cliff-villas.headline',
    summary: 'project.tebing-cliff-villas.summary',
    body: ['project.tebing-cliff-villas.body1', 'project.tebing-cliff-villas.body2', 'project.tebing-cliff-villas.body3'],
    hero: `${IMG}/villa-pool-top.jpg`,
    gallery: [`${IMG}/villa-pool-top.jpg`, `${IMG}/villa-terrace.jpg`, `${IMG}/villa-living-open.jpg`, `${IMG}/uluwatu-cliffs.jpg`],
    priceFromUsd: 595000,
    landSqm: 420,
    builtSqm: 310,
    bedrooms: 4,
    bathrooms: 4,
    leaseYears: 30,
    leaseExtensionYears: 20,
    leaseStartYear: 2026,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.74,
    nightlyRateUsd: 480,
    handover: 'project.tebing-cliff-villas.handover',
    handoverOrder: 20273,
    progress: 12,
    unitsTotal: 3,
    unitsAvailable: 3,
    features: ['project.tebing-cliff-villas.feature1', 'project.tebing-cliff-villas.feature2', 'project.tebing-cliff-villas.feature3', 'project.tebing-cliff-villas.feature4', 'project.tebing-cliff-villas.feature5', 'project.tebing-cliff-villas.feature6'],
    timeline: [
      { date: 'project.tebing-cliff-villas.timeline1.date', title: 'project.tebing-cliff-villas.timeline1.title', note: 'project.tebing-cliff-villas.timeline1.note', progress: 6 },
      { date: 'project.tebing-cliff-villas.timeline2.date', title: 'project.tebing-cliff-villas.timeline2.title', note: 'project.tebing-cliff-villas.timeline2.note', progress: 12 },
      { date: 'project.tebing-cliff-villas.timeline3.date', title: 'project.tebing-cliff-villas.timeline3.title', note: 'project.tebing-cliff-villas.timeline3.note', progress: 20 },
    ],
  },
  {
    id: 'p3',
    slug: 'sawah-ubud-retreat',
    pool: 'project.sawah-ubud-retreat.pool',
    name: 'project.sawah-ubud-retreat.name',
    area: 'ubud',
    type: 'villa',
    status: 'construction',
    headline: 'project.sawah-ubud-retreat.headline',
    summary: 'project.sawah-ubud-retreat.summary',
    body: ['project.sawah-ubud-retreat.body1', 'project.sawah-ubud-retreat.body2', 'project.sawah-ubud-retreat.body3'],
    hero: `${IMG}/villa-lawn.jpg`,
    gallery: [`${IMG}/villa-lawn.jpg`, `${IMG}/villa-dining-void.jpg`, `${IMG}/villa-bed-terrace.jpg`, `${IMG}/rice-ubud.jpg`],
    priceFromUsd: 312000,
    landSqm: 1100,
    builtSqm: 420,
    bedrooms: 6,
    bathrooms: 6,
    leaseYears: 25,
    leaseExtensionYears: 25,
    leaseStartYear: 2025,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.81,
    nightlyRateUsd: 200,
    handover: 'project.sawah-ubud-retreat.handover',
    handoverOrder: 20264,
    progress: 68,
    unitsTotal: 1,
    unitsAvailable: 1,
    features: ['project.sawah-ubud-retreat.feature1', 'project.sawah-ubud-retreat.feature2', 'project.sawah-ubud-retreat.feature3', 'project.sawah-ubud-retreat.feature4', 'project.sawah-ubud-retreat.feature5', 'project.sawah-ubud-retreat.feature6'],
    timeline: [
      { date: 'project.sawah-ubud-retreat.timeline1.date', title: 'project.sawah-ubud-retreat.timeline1.title', note: 'project.sawah-ubud-retreat.timeline1.note', progress: 10 },
      { date: 'project.sawah-ubud-retreat.timeline2.date', title: 'project.sawah-ubud-retreat.timeline2.title', note: 'project.sawah-ubud-retreat.timeline2.note', progress: 22 },
      { date: 'project.sawah-ubud-retreat.timeline3.date', title: 'project.sawah-ubud-retreat.timeline3.title', note: 'project.sawah-ubud-retreat.timeline3.note', progress: 52 },
      { date: 'project.sawah-ubud-retreat.timeline4.date', title: 'project.sawah-ubud-retreat.timeline4.title', note: 'project.sawah-ubud-retreat.timeline4.note', progress: 68 },
    ],
  },
  {
    id: 'p4',
    slug: 'batu-loft-townhouses',
    pool: 'project.batu-loft-townhouses.pool',
    name: 'project.batu-loft-townhouses.name',
    area: 'canggu',
    type: 'townhouse',
    status: 'construction',
    headline: 'project.batu-loft-townhouses.headline',
    summary: 'project.batu-loft-townhouses.summary',
    body: ['project.batu-loft-townhouses.body1', 'project.batu-loft-townhouses.body2', 'project.batu-loft-townhouses.body3'],
    hero: `${IMG}/villa-stair.jpg`,
    gallery: [`${IMG}/villa-stair.jpg`, `${IMG}/villa-kitchen.jpg`, `${IMG}/villa-lounge.jpg`, `${IMG}/canggu.jpg`],
    priceFromUsd: 248000,
    landSqm: 130,
    builtSqm: 148,
    bedrooms: 2,
    bathrooms: 2,
    leaseYears: 27,
    leaseExtensionYears: 20,
    leaseStartYear: 2025,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.84,
    nightlyRateUsd: 172,
    handover: 'project.batu-loft-townhouses.handover',
    handoverOrder: 20263,
    progress: 82,
    unitsTotal: 8,
    unitsAvailable: 3,
    features: ['project.batu-loft-townhouses.feature1', 'project.batu-loft-townhouses.feature2', 'project.batu-loft-townhouses.feature3', 'project.batu-loft-townhouses.feature4', 'project.batu-loft-townhouses.feature5', 'project.batu-loft-townhouses.feature6'],
    timeline: [
      { date: 'project.batu-loft-townhouses.timeline1.date', title: 'project.batu-loft-townhouses.timeline1.title', note: 'project.batu-loft-townhouses.timeline1.note', progress: 12 },
      { date: 'project.batu-loft-townhouses.timeline2.date', title: 'project.batu-loft-townhouses.timeline2.title', note: 'project.batu-loft-townhouses.timeline2.note', progress: 46 },
      { date: 'project.batu-loft-townhouses.timeline3.date', title: 'project.batu-loft-townhouses.timeline3.title', note: 'project.batu-loft-townhouses.timeline3.note', progress: 68 },
      { date: 'project.batu-loft-townhouses.timeline4.date', title: 'project.batu-loft-townhouses.timeline4.title', note: 'project.batu-loft-townhouses.timeline4.note', progress: 82 },
    ],
  },
  {
    id: 'p5',
    slug: 'segara-beachfront-villas',
    pool: 'project.segara-beachfront-villas.pool',
    name: 'project.segara-beachfront-villas.name',
    area: 'sanur',
    type: 'villa',
    status: 'coming-soon',
    headline: 'project.segara-beachfront-villas.headline',
    summary: 'project.segara-beachfront-villas.summary',
    body: ['project.segara-beachfront-villas.body1', 'project.segara-beachfront-villas.body2', 'project.segara-beachfront-villas.body3'],
    hero: `${IMG}/villa-living-open.jpg`,
    gallery: [`${IMG}/villa-living-open.jpg`, `${IMG}/villa-pool-water.jpg`, `${IMG}/villa-bath-twin.jpg`, `${IMG}/sanur.jpg`],
    priceFromUsd: 690000,
    landSqm: 350,
    builtSqm: 290,
    bedrooms: 4,
    bathrooms: 4,
    leaseYears: 30,
    leaseExtensionYears: 25,
    leaseStartYear: 2027,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.83,
    nightlyRateUsd: 340,
    handover: 'project.segara-beachfront-villas.handover',
    handoverOrder: 20281,
    progress: 4,
    unitsTotal: 2,
    unitsAvailable: 2,
    features: ['project.segara-beachfront-villas.feature1', 'project.segara-beachfront-villas.feature2', 'project.segara-beachfront-villas.feature3', 'project.segara-beachfront-villas.feature4', 'project.segara-beachfront-villas.feature5', 'project.segara-beachfront-villas.feature6'],
    timeline: [
      { date: 'project.segara-beachfront-villas.timeline1.date', title: 'project.segara-beachfront-villas.timeline1.title', note: 'project.segara-beachfront-villas.timeline1.note', progress: 4 },
    ],
  },
  {
    id: 'p6',
    slug: 'kayu-commercial-block',
    pool: 'project.kayu-commercial-block.pool',
    name: 'project.kayu-commercial-block.name',
    area: 'canggu',
    type: 'commercial',
    status: 'construction',
    headline: 'project.kayu-commercial-block.headline',
    summary: 'project.kayu-commercial-block.summary',
    body: ['project.kayu-commercial-block.body1', 'project.kayu-commercial-block.body2', 'project.kayu-commercial-block.body3'],
    hero: `${IMG}/villa-kitchen.jpg`,
    gallery: [`${IMG}/villa-kitchen.jpg`, `${IMG}/villa-dining-stair.jpg`, `${IMG}/villa-terrace.jpg`, `${IMG}/seminyak.jpg`],
    priceFromUsd: 860000,
    landSqm: 500,
    builtSqm: 720,
    bedrooms: 6,
    bathrooms: 8,
    leaseYears: 28,
    leaseExtensionYears: 20,
    leaseStartYear: 2026,
    projectedGrossYield: 19.4,
    projectedNetYield: 15.1,
    targetOccupancy: 0.88,
    nightlyRateUsd: 0,
    handover: 'project.kayu-commercial-block.handover',
    handoverOrder: 20272,
    progress: 22,
    unitsTotal: 1,
    unitsAvailable: 1,
    features: ['project.kayu-commercial-block.feature1', 'project.kayu-commercial-block.feature2', 'project.kayu-commercial-block.feature3', 'project.kayu-commercial-block.feature4', 'project.kayu-commercial-block.feature5', 'project.kayu-commercial-block.feature6'],
    timeline: [
      { date: 'project.kayu-commercial-block.timeline1.date', title: 'project.kayu-commercial-block.timeline1.title', note: 'project.kayu-commercial-block.timeline1.note', progress: 10 },
      { date: 'project.kayu-commercial-block.timeline2.date', title: 'project.kayu-commercial-block.timeline2.title', note: 'project.kayu-commercial-block.timeline2.note', progress: 22 },
    ],
  },
  {
    id: 'p7',
    slug: 'bukit-land-parcel-12',
    pool: 'project.bukit-land-parcel-12.pool',
    name: 'project.bukit-land-parcel-12.name',
    area: 'uluwatu',
    type: 'land',
    status: 'available',
    headline: 'project.bukit-land-parcel-12.headline',
    summary: 'project.bukit-land-parcel-12.summary',
    body: ['project.bukit-land-parcel-12.body1', 'project.bukit-land-parcel-12.body2', 'project.bukit-land-parcel-12.body3'],
    hero: `${IMG}/uluwatu-cliffs.jpg`,
    gallery: [`${IMG}/uluwatu-cliffs.jpg`, `${IMG}/uluwatu-2.jpg`, `${IMG}/tanah-lot.jpg`],
    priceFromUsd: 198000,
    landSqm: 1800,
    builtSqm: 0,
    bedrooms: 0,
    bathrooms: 0,
    leaseYears: 30,
    leaseExtensionYears: 25,
    leaseStartYear: 2026,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0,
    nightlyRateUsd: 0,
    handover: 'project.bukit-land-parcel-12.handover',
    handoverOrder: 99999,
    progress: 0,
    unitsTotal: 1,
    unitsAvailable: 1,
    features: ['project.bukit-land-parcel-12.feature1', 'project.bukit-land-parcel-12.feature2', 'project.bukit-land-parcel-12.feature3', 'project.bukit-land-parcel-12.feature4', 'project.bukit-land-parcel-12.feature5', 'project.bukit-land-parcel-12.feature6'],
    timeline: [
      { date: 'project.bukit-land-parcel-12.timeline1.date', title: 'project.bukit-land-parcel-12.timeline1.title', note: 'project.bukit-land-parcel-12.timeline1.note', progress: 0 },
    ],
  },
  {
    id: 'p8',
    slug: 'sungai-house',
    pool: 'project.sungai-house.pool',
    name: 'project.sungai-house.name',
    area: 'pererenan',
    type: 'villa',
    status: 'delivered',
    headline: 'project.sungai-house.headline',
    summary: 'project.sungai-house.summary',
    body: ['project.sungai-house.body1', 'project.sungai-house.body2', 'project.sungai-house.body3'],
    hero: 'media/villa-pool-aerial.jpg',
    gallery: [
      'media/villa-pool-aerial.jpg',
      'media/villa-facade.jpg',
      'media/villa-pool-lounge.jpg',
      'media/villa-deck.jpg',
      'media/villa-deck-pool.jpg',
    ],
    video: 'media/villa-tour-full.mp4',
    videoPoster: 'media/villa-tour-full-poster.jpg',
    priceFromUsd: 495000,
    landSqm: 420,
    builtSqm: 260,
    bedrooms: 3,
    bathrooms: 3,
    leaseYears: 25,
    leaseExtensionYears: 25,
    leaseStartYear: 2023,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.79,
    nightlyRateUsd: 340,
    handover: 'project.sungai-house.handover',
    handoverOrder: 0,
    progress: 100,
    unitsTotal: 1,
    unitsAvailable: 0,
    features: ['project.sungai-house.feature1', 'project.sungai-house.feature2', 'project.sungai-house.feature3', 'project.sungai-house.feature4', 'project.sungai-house.feature5', 'project.sungai-house.feature6'],
    timeline: [
      { date: 'project.sungai-house.timeline1.date', title: 'project.sungai-house.timeline1.title', note: 'project.sungai-house.timeline1.note', progress: 15 },
      { date: 'project.sungai-house.timeline2.date', title: 'project.sungai-house.timeline2.title', note: 'project.sungai-house.timeline2.note', progress: 72 },
      { date: 'project.sungai-house.timeline3.date', title: 'project.sungai-house.timeline3.title', note: 'project.sungai-house.timeline3.note', progress: 100 },
      { date: 'project.sungai-house.timeline4.date', title: 'project.sungai-house.timeline4.title', note: 'project.sungai-house.timeline4.note', progress: 100 },
    ],
  },
  {
    id: 'p9',
    slug: 'karang-nusa-villas',
    pool: 'project.karang-nusa-villas.pool',
    name: 'project.karang-nusa-villas.name',
    area: 'nusa-dua',
    type: 'villa',
    status: 'available',
    headline: 'project.karang-nusa-villas.headline',
    summary: 'project.karang-nusa-villas.summary',
    body: ['project.karang-nusa-villas.body1', 'project.karang-nusa-villas.body2', 'project.karang-nusa-villas.body3'],
    hero: `${IMG}/villa-pool-water.jpg`,
    gallery: [`${IMG}/villa-pool-water.jpg`, `${IMG}/villa-dressing.jpg`, `${IMG}/villa-bath-tub.jpg`, `${IMG}/nusa-dua.jpg`],
    priceFromUsd: 470000,
    landSqm: 400,
    builtSqm: 265,
    bedrooms: 3,
    bathrooms: 3,
    leaseYears: 30,
    leaseExtensionYears: 20,
    leaseStartYear: 2026,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.76,
    nightlyRateUsd: 320,
    handover: 'project.karang-nusa-villas.handover',
    handoverOrder: 20274,
    progress: 8,
    unitsTotal: 5,
    unitsAvailable: 4,
    features: ['project.karang-nusa-villas.feature1', 'project.karang-nusa-villas.feature2', 'project.karang-nusa-villas.feature3', 'project.karang-nusa-villas.feature4', 'project.karang-nusa-villas.feature5', 'project.karang-nusa-villas.feature6'],
    timeline: [
      { date: 'project.karang-nusa-villas.timeline1.date', title: 'project.karang-nusa-villas.timeline1.title', note: 'project.karang-nusa-villas.timeline1.note', progress: 8 },
    ],
  },
];

export const PILLARS: Pillar[] = [
  {
    index: '01',
    icon: 'safety-certificate',
    title: 'pillar1.title',
    description: 'pillar1.description',
  },
  {
    index: '02',
    icon: 'solution',
    title: 'pillar2.title',
    description: 'pillar2.description',
  },
  {
    index: '03',
    icon: 'camera',
    title: 'pillar3.title',
    description: 'pillar3.description',
  },
  {
    index: '04',
    icon: 'line-chart',
    title: 'pillar4.title',
    description: 'pillar4.description',
  },
];

export const PROCESS: ProcessStep[] = [
  {
    index: '01',
    icon: 'compass',
    title: 'processStep1.title',
    duration: 'processStep1.duration',
    description: 'processStep1.description',
    bullets: ['processStep1.bullet1', 'processStep1.bullet2', 'processStep1.bullet3', 'processStep1.bullet4'],
  },
  {
    index: '02',
    icon: 'environment',
    title: 'processStep2.title',
    duration: 'processStep2.duration',
    description: 'processStep2.description',
    bullets: ['processStep2.bullet1', 'processStep2.bullet2', 'processStep2.bullet3', 'processStep2.bullet4'],
  },
  {
    index: '03',
    icon: 'deployment-unit',
    title: 'processStep3.title',
    duration: 'processStep3.duration',
    description: 'processStep3.description',
    bullets: ['processStep3.bullet1', 'processStep3.bullet2', 'processStep3.bullet3', 'processStep3.bullet4'],
  },
  {
    index: '04',
    icon: 'tool',
    title: 'processStep4.title',
    duration: 'processStep4.duration',
    description: 'processStep4.description',
    bullets: ['processStep4.bullet1', 'processStep4.bullet2', 'processStep4.bullet3', 'processStep4.bullet4'],
  },
  {
    index: '05',
    icon: 'key',
    title: 'processStep5.title',
    duration: 'processStep5.duration',
    description: 'processStep5.description',
    bullets: ['processStep5.bullet1', 'processStep5.bullet2', 'processStep5.bullet3', 'processStep5.bullet4'],
  },
  {
    index: '06',
    icon: 'rise',
    title: 'processStep6.title',
    duration: 'processStep6.duration',
    description: 'processStep6.description',
    bullets: ['processStep6.bullet1', 'processStep6.bullet2', 'processStep6.bullet3', 'processStep6.bullet4'],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: 'testimonial1.quote',
    author: 'testimonial1.author',
    meta: 'testimonial1.meta',
  },
  {
    quote: 'testimonial2.quote',
    author: 'testimonial2.author',
    meta: 'testimonial2.meta',
  },
  {
    quote: 'testimonial3.quote',
    author: 'testimonial3.author',
    meta: 'testimonial3.meta',
  },
];

export const FAQS: FaqItem[] = [
  {
    question: 'faq1.question',
    answer: 'faq1.answer',
  },
  {
    question: 'faq2.question',
    answer: 'faq2.answer',
  },
  {
    question: 'faq3.question',
    answer: 'faq3.answer',
  },
  {
    question: 'faq4.question',
    answer: 'faq4.answer',
  },
  {
    question: 'faq5.question',
    answer: 'faq5.answer',
  },
  {
    question: 'faq6.question',
    answer: 'faq6.answer',
  },
];

export const STATS = [
  { value: '84', suffix: '', label: 'stat1.label' },
  { value: '29', suffix: '', label: 'stat2.label' },
  { value: '12.7', suffix: '%', label: 'stat3.label' },
  { value: '96', suffix: '%', label: 'stat4.label' },
];

// Yields are derived, never authored: a project that earns a nightly rate gets
// its figure from the same model the calculator on the project page uses.
for (const project of PROJECTS) {
  if (project.nightlyRateUsd > 0) {
    project.projectedGrossYield = grossYieldPct(
      project.nightlyRateUsd,
      project.targetOccupancy,
      project.priceFromUsd,
    );
    project.projectedNetYield = netYieldPct(
      project.nightlyRateUsd,
      project.targetOccupancy,
      project.priceFromUsd,
    );
  }
}

export const AREA_MAP = new Map(AREAS.map((a) => [a.id, a]));
