import { Area, FaqItem, Pillar, ProcessStep, Project, Testimonial } from './models';
import { grossYieldPct, netYieldPct } from './yield-model';

const IMG = 'img';

export const AREAS: Area[] = [
  {
    id: 'canggu',
    name: 'Canggu',
    subtitle: 'Badung · West coast',
    image: `${IMG}/canggu.jpg`,
    tagline: 'The island’s busiest rental engine.',
    description:
      'Surf breaks, co-working, and a year-round crowd that books at short notice. Highest turnover on the island, and the tightest land supply — which is exactly why the numbers still work here.',
    landPriceArePerYearUsd: 1850,
    avgNightlyRateUsd: 285,
    occupancy: 0.82,
    driveToAirportMin: 45,
    bestFor: ['Short-stay rental', 'Digital nomads', 'F&B and retail'],
  },
  {
    id: 'pererenan',
    name: 'Pererenan',
    subtitle: 'Badung · North of Canggu',
    image: `${IMG}/canggu-2.jpg`,
    tagline: 'Canggu demand, with room left to build.',
    description:
      'Rice fields, a river mouth and a slower street grid. Pererenan absorbs the overflow from Canggu at a lower land cost, and plots here still come with a view worth designing around.',
    landPriceArePerYearUsd: 1400,
    avgNightlyRateUsd: 260,
    occupancy: 0.79,
    driveToAirportMin: 50,
    bestFor: ['Villa investment', 'Families', 'Long-stay guests'],
  },
  {
    id: 'seminyak',
    name: 'Seminyak',
    subtitle: 'Badung · Central beach strip',
    image: `${IMG}/seminyak.jpg`,
    tagline: 'Mature, walkable, and reliably booked.',
    description:
      'The original premium strip: beach clubs, restaurants and a guest profile that pays for location rather than novelty. Little new land, so value sits in renovation and boutique density.',
    landPriceArePerYearUsd: 2100,
    avgNightlyRateUsd: 310,
    occupancy: 0.77,
    driveToAirportMin: 30,
    bestFor: ['Boutique suites', 'Premium ADR', 'Commercial ground floor'],
  },
  {
    id: 'uluwatu',
    name: 'Uluwatu',
    subtitle: 'Badung · The Bukit peninsula',
    image: `${IMG}/uluwatu-cliffs.jpg`,
    tagline: 'Cliffs, ocean, and the highest nightly rates.',
    description:
      'Limestone plateau above world-class surf. Building here is an engineering exercise — water, access, retaining walls — and the reward is a view no neighbour can build out.',
    landPriceArePerYearUsd: 1250,
    avgNightlyRateUsd: 395,
    occupancy: 0.74,
    driveToAirportMin: 40,
    bestFor: ['Luxury villas', 'Ocean views', 'Honeymoon market'],
  },
  {
    id: 'ubud',
    name: 'Ubud',
    subtitle: 'Gianyar · Central highlands',
    image: `${IMG}/rice-tegalalang.jpg`,
    tagline: 'Longer stays, steadier occupancy.',
    description:
      'Jungle, river valleys and terraced rice. Guests stay five nights instead of two, wellness operators sign multi-year leases, and seasonality is gentler than on the coast.',
    landPriceArePerYearUsd: 900,
    avgNightlyRateUsd: 240,
    occupancy: 0.8,
    driveToAirportMin: 75,
    bestFor: ['Wellness retreats', 'Long stays', 'Jungle villas'],
  },
  {
    id: 'sanur',
    name: 'Sanur',
    subtitle: 'Denpasar · East coast',
    image: `${IMG}/sanur.jpg`,
    tagline: 'Calm water, older guests, longer leases.',
    description:
      'A reef-protected shoreline, a flat beach path and the new international hospital district. Sanur rents to a repeat, longer-staying market that barely notices low season.',
    landPriceArePerYearUsd: 1150,
    avgNightlyRateUsd: 215,
    occupancy: 0.81,
    driveToAirportMin: 35,
    bestFor: ['Long stays', 'Retirement market', 'Family villas'],
  },
  {
    id: 'nusa-dua',
    name: 'Nusa Dua',
    subtitle: 'Badung · Southern enclave',
    image: `${IMG}/nusa-dua.jpg`,
    tagline: 'Resort-grade infrastructure, zoned and gated.',
    description:
      'Planned, serviced and regulated — the one part of Bali built to a masterplan. Permits are predictable, utilities are real, and the guest mix skews corporate and conference.',
    landPriceArePerYearUsd: 1550,
    avgNightlyRateUsd: 330,
    occupancy: 0.76,
    driveToAirportMin: 20,
    bestFor: ['Serviced villas', 'Corporate guests', 'Predictable permits'],
  },
  {
    id: 'tabanan',
    name: 'Tabanan',
    subtitle: 'Tabanan · North-west coast',
    image: `${IMG}/tanah-lot.jpg`,
    tagline: 'The next ten years, at today’s land price.',
    description:
      'Black-sand coastline past Tanah Lot, with the new coastal road shortening the drive every year. Entry cost is a third of Canggu — this is a land-banking play with a build option.',
    landPriceArePerYearUsd: 550,
    avgNightlyRateUsd: 195,
    occupancy: 0.68,
    driveToAirportMin: 70,
    bestFor: ['Land banking', 'Large plots', 'Early entry'],
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    slug: 'ombak-residences',
    pool: '9 m private pool',
    name: 'Ombak Residences',
    area: 'pererenan',
    type: 'villa',
    status: 'construction',
    headline: 'Four three-bedroom villas, one shared rice-field frontage.',
    summary:
      'A small cluster of 3-bedroom villas set back from Jalan Pantai Pererenan, each with a 9-metre pool and an open-air upper living deck.',
    body: [
      'Ombak sits on 1,400 m² of former rice field with a protected green belt on its northern edge — the view cannot be built out. Four villas share a private access road, a staff entrance and a single deep well, which keeps running costs per unit roughly 30% below a stand-alone build.',
      'Each villa is laid out for rental first: bedrooms on the ground floor with direct pool access, living and kitchen upstairs where the ceiling opens to a 5-metre ridge. The layout photographs well, which matters more to your booking rate than any finish we could specify.',
      'Construction is by our own site team under a fixed bill of quantities. You receive a photo set and a cost reconciliation every Friday until handover.',
    ],
    hero: `${IMG}/villa-pool-deck.jpg`,
    gallery: [`${IMG}/villa-pool-deck.jpg`, `${IMG}/villa-living-pool.jpg`, `${IMG}/villa-master.jpg`, `${IMG}/villa-lawn.jpg`],
    priceFromUsd: 389000,
    landSqm: 350,
    builtSqm: 245,
    bedrooms: 3,
    bathrooms: 3,
    leaseYears: 25,
    leaseExtensionYears: 25,
    leaseStartYear: 2026,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.79,
    nightlyRateUsd: 295,
    handover: 'Q1 2027',
    progress: 35,
    unitsTotal: 4,
    unitsAvailable: 2,
    features: ['9 m private pool', 'Rice-field frontage', 'Rooftop lounge', 'Staff quarters', 'Deep well + filtration', 'Solar hot water'],
    timeline: [
      { date: 'Mar 2026', title: 'Land secured, PT PMA registered', note: 'Due diligence closed, notarial lease signed for 25 + 25 years.', progress: 8 },
      { date: 'May 2026', title: 'IMB / PBG permit issued', note: 'Building permit approved for four units at 245 m² each.', progress: 18 },
      { date: 'Aug 2026', title: 'Foundations and pool shells poured', note: 'All four slabs complete; pool shells waterproofed and tested.', progress: 35 },
      { date: 'Dec 2026', title: 'Roof structure — scheduled', note: 'Bengkirai ridge beams pre-ordered and stored on site.', progress: 60 },
    ],
  },
  {
    id: 'p2',
    slug: 'tebing-cliff-villas',
    pool: '11 m infinity edge',
    name: 'Tebing Cliff Villas',
    area: 'uluwatu',
    type: 'villa',
    status: 'available',
    headline: 'Three cliff-edge villas, 120 metres above the Indian Ocean.',
    summary:
      'Uninterrupted west-facing ocean views with an 11-metre infinity pool cantilevered over the limestone edge.',
    body: [
      'The plot sits on the second row back from the cliff path, which means no public access along your boundary and a building line that Badung planning has already approved. Engineering was the hard part: a 4.5-metre retaining structure tied into bedrock, designed by our in-house structural engineer and independently checked.',
      'Nightly rates on this stretch of the Bukit are the highest we underwrite anywhere on the island. Occupancy is lower than Canggu, but the rate difference more than compensates — the net yield model assumes 74% and still clears 14%.',
      'Water is trucked and stored in a 30 m³ reservoir under the driveway, with UV and reverse-osmosis treatment. This is the single most common failure point in Bukit villas, and it is engineered, not improvised.',
    ],
    hero: `${IMG}/villa-pool-top.jpg`,
    gallery: [`${IMG}/villa-pool-top.jpg`, `${IMG}/villa-terrace.jpg`, `${IMG}/villa-living-open.jpg`, `${IMG}/uluwatu-cliffs.jpg`],
    priceFromUsd: 595000,
    landSqm: 420,
    builtSqm: 310,
    bedrooms: 4,
    bathrooms: 4,
    leaseYears: 30,
    leaseExtensionYears: 20,
    leaseStartYear: 2026,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.74,
    nightlyRateUsd: 480,
    handover: 'Q3 2027',
    progress: 12,
    unitsTotal: 3,
    unitsAvailable: 3,
    features: ['11 m infinity pool', 'Ocean-facing all rooms', '30 m³ water reservoir', 'RO + UV treatment', 'Engineered retaining wall', 'Backup generator'],
    timeline: [
      { date: 'Jun 2026', title: 'Land acquired', note: 'Certificate checked against Badung land office; zoning confirmed as tourism.', progress: 6 },
      { date: 'Sep 2026', title: 'Geotechnical survey complete', note: 'Bedrock at 2.1 m; retaining design finalised and externally verified.', progress: 12 },
      { date: 'Nov 2026', title: 'Permit submission — in progress', note: 'PBG application lodged; approval expected within 10 weeks.', progress: 20 },
    ],
  },
  {
    id: 'p3',
    slug: 'sawah-ubud-retreat',
    pool: '20 m shared lap pool',
    name: 'Sawah Ubud Retreat',
    area: 'ubud',
    type: 'villa',
    status: 'construction',
    headline: 'Six one-bedroom pavilions around a shared wellness deck.',
    summary:
      'A retreat-format build in the Petulu valley: six private pavilions, a yoga shala and a 20-metre lap pool, designed to be operated as one property.',
    body: [
      'Ubud rewards a different format. Guests stay five to nine nights, book earlier, and choose on atmosphere rather than proximity to a beach club. Sawah is built for that: individual pavilions for privacy, shared facilities for the operator’s margin.',
      'The whole site can be let as a single retreat venue — which is what a wellness operator will pay a multi-year fixed lease for. That option is what turns a low-twelves projected yield into a floor rather than a forecast.',
      'Structure is exposed bengkirai and local paras stone; roofs are alang-alang over a waterproof membrane, so you get the look without the five-year replacement cycle.',
    ],
    hero: `${IMG}/villa-lawn.jpg`,
    gallery: [`${IMG}/villa-lawn.jpg`, `${IMG}/villa-dining-void.jpg`, `${IMG}/villa-bed-terrace.jpg`, `${IMG}/rice-ubud.jpg`],
    priceFromUsd: 312000,
    landSqm: 1100,
    builtSqm: 420,
    bedrooms: 6,
    bathrooms: 6,
    leaseYears: 25,
    leaseExtensionYears: 25,
    leaseStartYear: 2025,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.81,
    nightlyRateUsd: 200,
    handover: 'Q4 2026',
    progress: 68,
    unitsTotal: 1,
    unitsAvailable: 1,
    features: ['Yoga shala', '20 m lap pool', 'Six private pavilions', 'Valley view', 'Operator-ready layout', 'Alang-alang over membrane'],
    timeline: [
      { date: 'Nov 2025', title: 'Land secured', note: '1,100 m² in Petulu; river-boundary setback confirmed with the banjar.', progress: 10 },
      { date: 'Feb 2026', title: 'Permits issued', note: 'PBG approved for six pavilions plus shared facilities.', progress: 22 },
      { date: 'Jun 2026', title: 'Structure topped out', note: 'All six pavilion frames erected; shala ring beam poured.', progress: 52 },
      { date: 'Sep 2026', title: 'Pool and hardscape', note: 'Lap pool tiled and filled; paras stone paving 70% laid.', progress: 68 },
    ],
  },
  {
    id: 'p4',
    slug: 'batu-loft-townhouses',
    pool: 'Private plunge pool',
    name: 'Batu Loft Townhouses',
    area: 'canggu',
    type: 'townhouse',
    status: 'construction',
    headline: 'Eight two-bedroom lofts, five minutes from Berawa beach.',
    summary:
      'A compact, high-turnover format for the Canggu market: two-storey lofts with a plunge pool each and a shared rooftop bar.',
    body: [
      'Land in Berawa no longer supports stand-alone villas at a sensible entry price. The townhouse format keeps your ticket under $250,000 and your nightly rate within $40 of a full villa — which is where the yield comes from.',
      'Each loft has its own 4 × 3 m plunge pool, an outdoor shower and a covered parking bay. The shared rooftop is operated by the management company and generates a second revenue line from non-resident guests.',
      'Delivery is the closest of any project we have open: the structure is complete and we are in second fix.',
    ],
    hero: `${IMG}/villa-stair.jpg`,
    gallery: [`${IMG}/villa-stair.jpg`, `${IMG}/villa-kitchen.jpg`, `${IMG}/villa-lounge.jpg`, `${IMG}/canggu.jpg`],
    priceFromUsd: 248000,
    landSqm: 130,
    builtSqm: 148,
    bedrooms: 2,
    bathrooms: 2,
    leaseYears: 27,
    leaseExtensionYears: 20,
    leaseStartYear: 2025,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.84,
    nightlyRateUsd: 172,
    handover: 'Q3 2026',
    progress: 82,
    unitsTotal: 8,
    unitsAvailable: 3,
    features: ['Private plunge pool', 'Shared rooftop bar', 'Covered parking', '5 min to Berawa', 'Fibre + backup power', 'Furniture package included'],
    timeline: [
      { date: 'Aug 2025', title: 'Groundbreaking', note: 'Eight footings poured; site office and staff facilities installed.', progress: 12 },
      { date: 'Jan 2026', title: 'Structure complete', note: 'All eight units topped out; rooftop slab poured.', progress: 46 },
      { date: 'Apr 2026', title: 'First fix complete', note: 'Electrical, plumbing and pool plant roughed in and pressure tested.', progress: 68 },
      { date: 'Jul 2026', title: 'Second fix in progress', note: 'Joinery installed in units 1–5; pools filled and commissioned.', progress: 82 },
    ],
  },
  {
    id: 'p5',
    slug: 'segara-beachfront-villas',
    pool: '12 m pool + beach pavilion',
    name: 'Segara Beachfront Villas',
    area: 'sanur',
    type: 'villa',
    status: 'coming-soon',
    headline: 'Two beachfront villas on the last unbuilt plot in north Sanur.',
    summary:
      'Direct access to the reef-protected shoreline, with a 700 m² plot split into two four-bedroom villas.',
    body: [
      'Beachfront leasehold in Sanur almost never reaches the open market. This plot came to us through a family we have worked with since 2019, and we are releasing it to our existing clients first.',
      'Sanur’s guest profile is older, stays longer and books directly — which means lower channel fees and far less seasonality than the west coast. The trade-off is a lower nightly rate, and the model reflects that honestly.',
      'Registration of interest opens now; we will not take a deposit before the notarial due diligence pack is in your hands.',
    ],
    hero: `${IMG}/villa-living-open.jpg`,
    gallery: [`${IMG}/villa-living-open.jpg`, `${IMG}/villa-pool-water.jpg`, `${IMG}/villa-bath-twin.jpg`, `${IMG}/sanur.jpg`],
    priceFromUsd: 690000,
    landSqm: 350,
    builtSqm: 290,
    bedrooms: 4,
    bathrooms: 4,
    leaseYears: 30,
    leaseExtensionYears: 25,
    leaseStartYear: 2027,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.83,
    nightlyRateUsd: 340,
    handover: 'Q1 2028',
    progress: 4,
    unitsTotal: 2,
    unitsAvailable: 2,
    features: ['Direct beach access', 'Reef-protected swimming', '4 bedrooms', 'Beach pavilion', 'Sunrise orientation', 'Low seasonality'],
    timeline: [
      { date: 'Sep 2026', title: 'Plot under option', note: 'Exclusive option signed; legal due diligence commissioned.', progress: 4 },
    ],
  },
  {
    id: 'p6',
    slug: 'kayu-commercial-block',
    pool: 'No pool',
    name: 'Kayu Commercial Block',
    area: 'canggu',
    type: 'commercial',
    status: 'construction',
    headline: 'Ground-floor retail with six serviced studios above.',
    summary:
      'A mixed-use block on Jalan Pantai Batu Bolong: three retail bays at street level, six serviced studios on the two floors above.',
    body: [
      'Commercial leases in Canggu are signed two to five years in advance and paid annually up front. That changes the cash-flow shape of the asset completely — the retail bays alone cover the operating cost of the whole building.',
      'The studios above are let monthly to long-stay guests rather than nightly, which removes most of the housekeeping and channel cost. Blended, the block underwrites at 15.1% net.',
      'This is the format we recommend to investors who want yield without the operational drama of a nightly-rate villa.',
    ],
    hero: `${IMG}/villa-kitchen.jpg`,
    gallery: [`${IMG}/villa-kitchen.jpg`, `${IMG}/villa-dining-stair.jpg`, `${IMG}/villa-terrace.jpg`, `${IMG}/seminyak.jpg`],
    priceFromUsd: 860000,
    landSqm: 500,
    builtSqm: 720,
    bedrooms: 6,
    bathrooms: 8,
    leaseYears: 28,
    leaseExtensionYears: 20,
    leaseStartYear: 2026,
    projectedGrossYield: 19.4,
    projectedNetYield: 15.1,
    targetOccupancy: 0.88,
    nightlyRateUsd: 0,
    handover: 'Q2 2027',
    progress: 22,
    unitsTotal: 1,
    unitsAvailable: 1,
    features: ['3 retail bays', '6 serviced studios', 'Annual lease pre-payment', 'Street frontage 18 m', '3-phase power', 'Lift installed'],
    timeline: [
      { date: 'Apr 2026', title: 'Land and permits secured', note: 'Commercial zoning confirmed; PBG issued for three storeys.', progress: 10 },
      { date: 'Aug 2026', title: 'Piling and ground slab', note: 'Bored piles to 9 m; ground slab poured and cured.', progress: 22 },
    ],
  },
  {
    id: 'p7',
    slug: 'bukit-land-parcel-12',
    pool: 'Not built',
    name: 'Bukit Land Parcel 12',
    area: 'uluwatu',
    type: 'land',
    status: 'available',
    headline: '1,800 m² of zoned land, 600 m from Bingin beach.',
    summary:
      'A cleared, road-accessed and legally verified plot — buy the land now, build with us when you are ready.',
    body: [
      'Not every investor wants to start building on day one. This parcel is sold as a clean leasehold with a full due-diligence pack: certificate history, zoning confirmation, banjar consent and a boundary survey.',
      'We hold a design study for the plot showing three villas at 240 m² each within the permitted building coverage. You are under no obligation to use it, or us.',
      'Land here has moved roughly 14% a year for the last six years. We will show you the comparable transactions we used, not just the headline.',
    ],
    hero: `${IMG}/uluwatu-cliffs.jpg`,
    gallery: [`${IMG}/uluwatu-cliffs.jpg`, `${IMG}/uluwatu-2.jpg`, `${IMG}/tanah-lot.jpg`],
    priceFromUsd: 198000,
    landSqm: 1800,
    builtSqm: 0,
    bedrooms: 0,
    bathrooms: 0,
    leaseYears: 30,
    leaseExtensionYears: 25,
    leaseStartYear: 2026,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0,
    nightlyRateUsd: 0,
    handover: 'Immediate',
    progress: 0,
    unitsTotal: 1,
    unitsAvailable: 1,
    features: ['Zoned for tourism', 'Road access in place', 'Boundary survey done', 'Banjar consent obtained', 'Design study included', '600 m to Bingin'],
    timeline: [
      { date: 'Feb 2026', title: 'Due diligence pack complete', note: 'Certificate history, zoning letter and survey available on request.', progress: 0 },
    ],
  },
  {
    id: 'p8',
    slug: 'sungai-house',
    pool: '12 m pool over the river',
    name: 'Sungai House',
    area: 'pererenan',
    type: 'villa',
    status: 'delivered',
    headline: 'Our reference build: a three-bedroom villa on the river, delivered and operating.',
    summary:
      'Two storeys over a 12-metre pool that runs along the river boundary, with a sunken lounge set into the deck. Delivered in 2025 and let since.',
    body: [
      'Sungai House is the property we point people to when they ask what actually happens after handover. It sits on a river plot in Pererenan with a protected green boundary, which is why the pool could run the full length of the site instead of being tucked beside the building.',
      'The layout is a hybrid brief: the owner uses it for roughly ten weeks a year, and it is let for the rest. The upper floor carries an owner\u2019s suite that locks and is serviced separately, so personal belongings stay in place while the rest of the villa works.',
      'Everything on this page \u2014 the photographs, the walkthrough, the operating figures \u2014 comes from this building rather than from a render. Ask us for the twelve-month statement and we will send it.',
    ],
    hero: 'media/villa-pool-aerial.jpg',
    gallery: [
      'media/villa-pool-aerial.jpg',
      'media/villa-facade.jpg',
      'media/villa-pool-lounge.jpg',
      'media/villa-deck.jpg',
      'media/villa-deck-pool.jpg',
    ],
    video: 'media/villa-tour-full.mp4',
    videoPoster: 'media/villa-tour-full-poster.jpg',
    priceFromUsd: 495000,
    landSqm: 420,
    builtSqm: 260,
    bedrooms: 3,
    bathrooms: 3,
    leaseYears: 25,
    leaseExtensionYears: 25,
    leaseStartYear: 2023,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.79,
    nightlyRateUsd: 340,
    handover: 'Delivered 2025',
    progress: 100,
    unitsTotal: 1,
    unitsAvailable: 0,
    features: [
      '12 m pool along the river',
      'Sunken poolside lounge',
      'Owner\u2019s suite that locks',
      'Full-height glazing to the deck',
      'Delivered and operating since 2025',
      'Twelve-month statement available',
    ],
    timeline: [
      { date: 'Mar 2024', title: 'Construction start', note: 'Two storeys, 260 m\u00b2, on a 420 m\u00b2 river plot.', progress: 15 },
      { date: 'Nov 2024', title: 'Pool and deck complete', note: 'Pool shell tested and tiled; ironwood deck laid over the full frontage.', progress: 72 },
      { date: 'Feb 2025', title: 'Handover', note: 'Snagging closed, furniture installed, photography and listing prepared before the keys.', progress: 100 },
      { date: 'Mar 2025', title: 'Operations start', note: 'First guests three weeks after handover; owner statements monthly since.', progress: 100 },
    ],
  },
  {
    id: 'p9',
    slug: 'karang-nusa-villas',
    pool: '10 m private pool',
    name: 'Karang Nusa Villas',
    area: 'nusa-dua',
    type: 'villa',
    status: 'available',
    headline: 'Five serviced villas inside the Nusa Dua enclave.',
    summary:
      'Gated, serviced and zoned — the lowest-friction permit environment in Bali, with resort-grade utilities already at the boundary.',
    body: [
      'Nusa Dua is the only masterplanned district on the island. Power, water, drainage and fibre arrive at the plot boundary, the road is maintained, and the permit path is measured in weeks rather than quarters.',
      'The guest profile is different from the west coast: corporate travel, conferences and families who want a pool without a scooter. Occupancy is steadier, and cancellations are rarer.',
      'Five villas, three bedrooms each, delivered turnkey with a furniture package specified for rental durability rather than showroom appeal.',
    ],
    hero: `${IMG}/villa-pool-water.jpg`,
    gallery: [`${IMG}/villa-pool-water.jpg`, `${IMG}/villa-dressing.jpg`, `${IMG}/villa-bath-tub.jpg`, `${IMG}/nusa-dua.jpg`],
    priceFromUsd: 470000,
    landSqm: 400,
    builtSqm: 265,
    bedrooms: 3,
    bathrooms: 3,
    leaseYears: 30,
    leaseExtensionYears: 20,
    leaseStartYear: 2026,
    projectedGrossYield: 0,
    projectedNetYield: 0,
    targetOccupancy: 0.76,
    nightlyRateUsd: 320,
    handover: 'Q4 2027',
    progress: 8,
    unitsTotal: 5,
    unitsAvailable: 4,
    features: ['Gated enclave', 'Utilities at boundary', 'Fast permit path', 'Turnkey furniture', '3 bedrooms + study', 'Resort beach access'],
    timeline: [
      { date: 'Jul 2026', title: 'Lease signed', note: 'Thirty-year lease over 2,000 m² registered with the notary.', progress: 8 },
    ],
  },
];

export const PILLARS: Pillar[] = [
  {
    index: '01',
    icon: 'safety-certificate',
    title: 'Land you can actually hold',
    description:
      'Certificate history, zoning, banjar consent and a boundary survey — checked by our notary before a rupiah moves. If a plot fails, we tell you and walk away from our own commission.',
  },
  {
    index: '02',
    icon: 'solution',
    title: 'Designed by the people who build it',
    description:
      'Architect, structural engineer and quantity surveyor are on our payroll, not subcontracted. The drawing you approve is the building you receive, priced line by line.',
  },
  {
    index: '03',
    icon: 'camera',
    title: 'A build you can watch from home',
    description:
      'Photographs every Friday, costs reconciled against the original bill of quantities every month. Variances are explained while they are still small.',
  },
  {
    index: '04',
    icon: 'line-chart',
    title: 'An asset, not an ornament',
    description:
      'Our operations team lists, staffs and runs the property after handover, and reports what it earned and what it cost — in one statement, every month.',
  },
];

export const PROCESS: ProcessStep[] = [
  {
    index: '01',
    icon: 'compass',
    title: 'Brief and budget',
    duration: 'Week 1–2',
    description:
      'We start from what you want the asset to do — yield, personal use, resale horizon — and work backwards to an area, a plot size and a realistic total cost.',
    bullets: ['Investment brief', 'Area shortlist', 'All-in budget range', 'No fee, no obligation'],
  },
  {
    index: '02',
    icon: 'environment',
    title: 'Land sourcing and due diligence',
    duration: 'Week 3–10',
    description:
      'Our land scouts work the areas you shortlisted. Every candidate plot gets a legal pack before you see a price: certificate chain, zoning, access, water and banjar position.',
    bullets: ['Off-market sourcing', 'Notarial verification', 'Zoning confirmation', 'PT PMA structuring'],
  },
  {
    index: '03',
    icon: 'deployment-unit',
    title: 'Design and costing',
    duration: 'Week 8–16',
    description:
      'Concept, then developed design, then a bill of quantities priced item by item. You sign off on a fixed BOQ — not a square-metre estimate that drifts.',
    bullets: ['In-house architect', 'Structural engineering', 'Line-item BOQ', 'Fixed-price contract'],
  },
  {
    index: '04',
    icon: 'tool',
    title: 'Permits and construction',
    duration: 'Month 4–18',
    description:
      'PBG permit, then groundworks. Our own site team builds it: supervisors, quality control and a quantity surveyor reconciling spend against the BOQ every month.',
    bullets: ['PBG / IMB handled', 'Own construction crew', 'Weekly photo report', 'Monthly cost reconciliation'],
  },
  {
    index: '05',
    icon: 'key',
    title: 'Snagging and handover',
    duration: 'Month 18–20',
    description:
      'An independent snagging list, then defects cleared before you sign. Furniture, utilities and licences are in place on the day you receive the keys.',
    bullets: ['Independent snag list', 'Utilities connected', 'Furniture installed', '12-month defects cover'],
  },
  {
    index: '06',
    icon: 'rise',
    title: 'Operations and reporting',
    duration: 'Ongoing',
    description:
      'Our operations team takes over: listings, pricing, guests, staff, maintenance. One statement a month showing revenue, cost and what landed in your account.',
    bullets: ['Multi-channel listing', 'Dynamic pricing', '24/7 guest reception', 'Monthly owner statement'],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote:
      'I bought a plot I had only seen on video, from Istanbul. What made it work was the Friday photo set — twenty months of it. I never once had to ask where my money had gone.',
    author: 'Deniz A.',
    meta: 'Pererenan · delivered 2025',
  },
  {
    quote:
      'The bill of quantities was 340 lines long and I understood maybe half of it. Their QS went through it with me twice. Final cost came in 2.1% over the contract — and they had flagged every item before it happened.',
    author: 'Mark R.',
    meta: 'Uluwatu · delivered 2024',
  },
  {
    quote:
      'Handover was not the end of the relationship, which is what I had been warned about. The villa was listed three weeks later and I have had a statement on the fifth of every month since.',
    author: 'Sophie L.',
    meta: 'Ubud · operating since 2023',
  },
];

export const FAQS: FaqItem[] = [
  {
    question: 'Can a foreigner own property in Bali?',
    answer:
      'Yes — through leasehold (Hak Sewa), or through an Indonesian company (PT PMA) holding a right-to-build title (HGB). Freehold stays with Indonesian nationals, so we structure every project one of those two ways, and the notary walks you through the difference before you sign anything.',
  },
  {
    question: 'What actually happens when the lease expires?',
    answer:
      'A lease is a contract for a fixed number of years — typically 25 or 30, with an extension period agreed and pre-paid at the start. At expiry the land returns to the owner unless the extension is exercised or a new term is negotiated. We register the extension option notarially on day one, so your right to extend is on the public record from the start.',
  },
  {
    question: 'How much does it cost to build, per square metre?',
    answer:
      'Between roughly $650 and $1,100 per m² of built area for the quality level we work at, excluding land, pool, landscaping and furniture. The range is wide because site access, retaining works and water supply vary enormously between Canggu and the Bukit. We price a bill of quantities per project rather than quoting a rate.',
  },
  {
    question: 'How long does a villa take?',
    answer:
      'Twelve to eighteen months on site for a typical three-bedroom villa, plus two to four months beforehand for permits. Add land sourcing and due diligence and a realistic end-to-end figure is twenty to twenty-four months from first conversation to first guest.',
  },
  {
    question: 'Are the projected yields guaranteed?',
    answer:
      'What we can stand behind is where the numbers come from. Every figure on this site is underwritten from our own operating data on delivered properties in the same area, and we will show you the statements behind it. They are projections rather than guarantees — occupancy, rates and regulation all move — so treat them as a well-evidenced range.',
  },
  {
    question: 'Do I have to use your management company?',
    answer:
      'That is entirely your choice. Most owners stay with us because it is the same team that built the property and they already know where every valve and cable is. The construction contract and the management agreement are separate documents, so you are free to sign one without the other.',
  },
];

export const STATS = [
  { value: '84', suffix: '', label: 'Villas delivered since 2016' },
  { value: '29', suffix: '', label: 'People on the payroll' },
  { value: '12.7', suffix: '%', label: 'Median net yield, delivered portfolio' },
  { value: '96', suffix: '%', label: 'Delivered on or before contract date' },
];

// Yields are derived, never authored: a project that earns a nightly rate gets
// its figure from the same model the calculator on the project page uses.
for (const project of PROJECTS) {
  if (project.nightlyRateUsd > 0) {
    project.projectedGrossYield = grossYieldPct(
      project.nightlyRateUsd,
      project.targetOccupancy,
      project.priceFromUsd,
    );
    project.projectedNetYield = netYieldPct(
      project.nightlyRateUsd,
      project.targetOccupancy,
      project.priceFromUsd,
    );
  }
}

export const AREA_MAP = new Map(AREAS.map((a) => [a.id, a]));
